//
// Created by conor on 14/04/18.
//

#ifndef PROJ_ANDROID_STUDIO_TIMETABLESYSTEM_H
#define PROJ_ANDROID_STUDIO_TIMETABLESYSTEM_H


class TimetableSystem {

};


#endif //PROJ_ANDROID_STUDIO_TIMETABLESYSTEM_H
