//
// Created by conor on 04/03/18.
//

#ifndef PROJ_ANDROID_STUDIO_STOPPINGLOCATION_H
#define PROJ_ANDROID_STUDIO_STOPPINGLOCATION_H


class StoppingLocation {

};


#endif //PROJ_ANDROID_STUDIO_STOPPINGLOCATION_H
